### ISSUE TITLE
Meaning of Sizes BF, DimOrder BF, DimOrder BF Array, DimOrder

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [filippocastelli/pyometiff#14]
Dear all,

Could you clarify a bit exact meaning of Sizes BF, DimOrder BF, DimOrder BF Array, DimOrder fields in metadata?

Thank you for any input.

**Comment by filippocastelli** [comment]
Hi, thank you for opening the issue.
Sorry for the poor documentation of the project, some of the terminology is obscure and tied to the inital uses of this code as part of my previous research, this will need to be addressed in the future.


`DimOrder BF` should be the  `DimensionOrder` field of the `Pixels`  of the current image series, the values should reflect the ones in the OMEXML schema https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Pixels_DimensionOrder

`DimOrder BF Array` is just a reversed version of `DimOrder BF`, while `DimOrder` should be a copy of `DimOrder BF Array`.

`Sizes BF` is an array composed of 
- `TotalSeries` which is the number of `Image` nodes in the OMEXML root
- `SizeT`, `SizeZ`, `SizeC`, `SizeY`, `SizeX` relative to the current image series, which are defined in the OMEXML schema https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Pixels_SizeT

I know this is very confusing, very obscure and specific to legacy applications, to be honest I don't even remember the reasons for this particular naming ( it probably made sense back then ). 
`reader.metadata` is just a summarization of the fields that are present in the OMEXML object, which you can read at `reader.ox`, all the names in `reader.ox` should be faithful to the OMEXML schema (if I did things right).

Again, sorry for the confusion

**Comment by aliaksei-chareshneu** [comment]
Thank you very much for the clarification. No worries, I understand that it is difficult to handle these. Thank you very much for developing this package!
