### ISSUE TITLE
missing metadata entries

### ISSUE THREAD

**Issue by irelamb** [filippocastelli/pyometiff#15]
Hi Filippo,

thank you very much for your code, it's very useful. However I think some OME metadata entries are missing in your code, in particular 'TimeIncrement' and 'TimeIncrementUnit'. I would suggest to add them, they are important when dealing with time series.

Best,
Irene

**Comment by filippocastelli** [comment]
Hey there!

It's very possible that I overlooked some metadata entries related to time series as I didn't work with them directly.
I'll add `TimeIncrement` and `TimeIncrementUnit` asap, did you notice other missing fields that you might need?

Filippo

**Comment by irelamb** [comment]
Thank you for the prompt reply! Those are the only ones that I noticed, everything else seems fine to me.

**Comment by filippocastelli** [comment]
Hi Irene!
Release `1.0.1` should support reading and writing `TimeIncrement` and `TimeIncrementUnit` metadata.
to upgrade just run `pip install --upgrade pyometiff`
let me know if you encounter any issues
I'm closing the issue for now, but feel free to re-open another one if needed
