### ISSUE TITLE
TiffFrame 1: missing required tags OME series: expected 1 frames, got 2

### ISSUE THREAD

**Issue by arjunrajanna** [filippocastelli/pyometiff#4]
Hello,

Thank you very much for providing a smooth interface to open OME TIF.

When I try and open the .OME.TIFF file that I have, I get the following error:
**TiffFrame 1: missing required tags
OME series: expected 1 frames, got 2**

import pathlib
from pyometiff import OMETIFFReader

img_fpath = pathlib.Path("/path_to_file/file.ome.tiff")

reader = OMETIFFReader(fpath=img_fpath)

img_array, metadata, xml_metadata = reader.read()

Your thoughts on this would be greatly appreciated! 

Best,

**Comment by filippocastelli** [comment]
Hi!
Would it possible to have the file? It would help me to investigate the issue
