### ISSUE TITLE
parse_metadata for user-supplied xml string

### ISSUE THREAD

**Issue by vladpopovici** [filippocastelli/pyometiff#6]
I try to parse an OME XML string read outside the OMETIFFReader object, using the OMETIFFReader.parse_metadata(s) function. However, this function always parses the internal attribute "self.omexml_string" instead of the argument string ("omexml_string"). I suggest modifying line 54 from pyometiff/omereader.py by dropping "self." from "self.omexml_string".

Thanks a lot for this nice package!

**Comment by filippocastelli** [comment]
uh, that's definetly a typo on my part! 
Thank you for noticing and opening the issue, I'll fix it and draft a new release ASAP.

**Comment by filippocastelli** [comment]
Solved issue in 27e5c5b87fa3d9650e993f491d387b55882636ae and published fix on release 0.0.12, which you should now be able to install via `pip install --upgrade pyometiff`
Thanks for contributing!
